require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PEyes' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-mail', :path => '../node_modules/react-native-mail'

  target 'PEyesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'PEyes-tvOS' do
  # Pods for PEyes-tvOS

  target 'PEyes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

pod 'Firebase/Analytics'
pod 'GoogleMLKit/TextRecognition'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
